version: '3.7'

services:
  daneradaroweapi:
    image: ${DOCKER_REGISTRY-}daneradaroweapi
    container_name: daneradarowe_api
    ports:
        - 80:80
        - 443:443
    build:
      context: .
      dockerfile: DaneradaroweApi/Dockerfile
    networks:
      - daneradarowe
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: daneradarowe_mysql
    ports:
      - 3306:3306
    networks:
      - daneradarowe
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=daneradarowe
      - MYSQL_PASSWORD=daneradarowe

networks:
  daneradarowe:
    name: daneradarowe-network